### ISSUE TITLE
UK / GB , scraping US store by default

### ISSUE THREAD

**Issue by rwzdoorn** [facundoolano/app-store-scraper#101]
First off: Big thank you for creating this scraper!!

* Operating System: **CentOS7**
* Node version: **v10.16.0**
* app-store-scraper version: **6.9.0**

### Description: 
I'm using this scraper to scrape multiple countries like NL, BE, US, CA and UK (or is it GB?). The scraper works for all except United Kingdom / Great Britain. I've been using UK and GB as country but it gives me same rating as US (which is the default). What is the country code for UK/GB to use this script?

Thanks in advance!

**Comment by b-reynolds** [comment]
Hey @rwzdoorn did you ever manage to figure this out? I've just stumbled across the same issue with 1dd0f02.
