### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by bhupendra-dudhwal** [facundoolano/app-store-scraper#106]
Hi,
I am getting an error while fetching android package details :-1: 
Package name:-  com.tvappagency.WeatherNation
this is an valid package .

Play store Url:- 
https://play.google.com/store/apps/details?id=com.tvappagency.WeatherNation

**Comment by facundoolano** [comment]
This is app-store-scraper not google-play-scraper.
