### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by arddluma** [facundoolano/app-store-scraper#109]
I got this error when I try to access from my admin dashboard.

> Access to fetch at 'https://itunes.apple.com/lookup?id=xxxxxx&country=us&entity=software' from origin 'https://xxxx.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'http://localhost:3000' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by yurganov** [comment]
You cannot run this library from browser.

You should run standalone server on NodeJS and connect to it from browser.
