### ISSUE TITLE
Can't Get Reviews and score values

### ISSUE THREAD

**Issue by bameur** [facundoolano/app-store-scraper#115]
Hi,
I  do not have the following values in response:
score: undefined,
reviews: undefined,
currentVersionScore: undefined,
currentVersionReviews: undefined,

ratings: 0,
histogram: {}

can you help me solve this problem?

Thanks.

**Comment by yurganov** [comment]
Give us sample of your code and app id

**Comment by bameur** [comment]
Thank you for your reply.

The cause of my problem is the country option. Now everything is functional.

store.app({id: xxxxxxxxxxxx, ratings: true### , country: 'fr'}).then(console.log).catch(console.log);

Thank you in advance.

**Comment by yurganov** [comment]
So, if everything is works, can you close ticket?
