### ISSUE TITLE
The rating of the application obtained is not the same as the apple website

### ISSUE THREAD

**Issue by bameur** [facundoolano/app-store-scraper#116]
Hello.
I have an abnormal library behavior. the rating and the number of ratings I get via the calling website is not the same as the feedback from app-store-scraper. can you help me to identify the cause? 

here is the detail :

website : https://apps.apple.com/fr/app/enki/id1187914242

app-store-scraper 
**Request :**
store.ratings({id: '1187914242', appId: 'com.leroymerlin.enki.store', country: 'fr'}).then(console.log).catch(console.log);
**Result :** 
{
  ratings: 1571,
  histogram: { '1': 150, '2': 106, '3': 328, '4': 465, '5': 522 }
}
**Request:**
store.app({appId:'com.leroymerlin.enki.store', id: 1187914242, ratings: true, country: 'fr'}).then(console.log).catch(console.log);
**Result:**

{
  id: 1187914242,
  appId: 'com.leroymerlin.enki.store',
  title: 'Enki',
  url: 'https://apps.apple.com/fr/app/enki/id1187914242?uo=4',
  . . . . . .
  score: 3.5,
  reviews: 1743,
  currentVersionScore: 3.5,
  currentVersionReviews: 104,
  . . . . . .
  ratings: 1571,
  histogram: { '1': 150, '2': 106, '3': 328, '4': 465, '5': 522 }
}

Thank you

**Comment by b-reynolds** [comment]
I haven't got time to check right now but this could be an issue with the iTunes Search API if that's the source for this value.

References

- https://forums.developer.apple.com/thread/97704
- https://discussions.apple.com/thread/4920253

**Comment by b-reynolds** [comment]
The [solution](https://discussions.apple.com/thread/4920253) suggested by ME_Texan does not appear to work for me as there are still discrepancies between the site/api results when matching store countries.

https://apps.apple.com/gb/app/google-chrome/id535886823

6.3K Ratings
3.6 out of 5

http://itunes.apple.com/lookup?id=535886823&country=gb

```
{
    "averageUserRating": 3.5,
    "userRatingCountForCurrentVersion": 34,
    "userRatingCount": 18136
}
```

**Comment by bameur** [comment]
Thank you for your prompt response. 

This is the following url which send a wrong answer :
https://itunes.apple.com/FR/customer-reviews/id1187914242?displayable-kind=11

**Response :** 
{"adamId":1187914242,"clickToRateUrl":"https://userpub.itunes.apple.com/WebObjects/MZUserPublishing.woa/wa/userRateContent?displayable-kind=11&id=1187914242","writeUserReviewUrl":"https://userpub.itunes.apple.com/WebObjects/MZUserPublishing.woa/wa/writeUserReview?cc=fr&displayable-kind=11&id=1187914242","totalNumberOfReviews":268,"userReviewsRowUrl":"https://itunes.apple.com/WebObjects/MZStore.woa/wa/userReviewsRow","userReviewsSortOptions":[{"sortId":1,"name":"Les plus utiles"},{"sortId":2,"name":"Les plus favorables"},{"sortId":3,"name":"Les plus critiques"},{"sortId":4,"name":"Les plus récents"}],"kindId":11,"kindExtId":"iosSoftware","kindName":"software","saveUserReviewUrl":"https://userpub.itunes.apple.com/WebObjects/MZUserPublishing.woa/wa/saveUserReview?displayable-kind=11","ariaLabelForRatings":"3 étoiles et demie","ratingCount":1743,"ratingCountList":[222,125,349,486,561],"ratingAverage":3.5,"currentVersion":{"ariaLabelForRatings":"3 étoiles et demie","ratingCount":1571,"ratingCountList":[150,106,328,465,522],"ratingAverage":3.5}}

**Comment by bameur** [comment]
Hello 

here is the alternative solution that I found:

const rp         = require('request-promise');

var resultatRequest    = rp(`https://apps.apple.com/fr/app/google-chrome/id535886823`);

Promise.all([resultatRequest]).then(values => { 
  var resultWebApple = values[0];
  // Ratings Apple apps  Web --------------

    const $ = cheerio.load(resultWebApple);
    const ratingsMatchAppleWeb = $('.we-customer-ratings__averages__display').text();  // .match(/\d+/);
    console.log(ratingsMatchAppleWeb);
    //const ratingsAppleWeb = Array.isArray(ratingsMatchAppleWeb) ? parseInt(ratingsMatchAppleWeb[0]) : 0;

    console.log("Rating = " + ratingsMatchAppleWeb);

}

Tks
