### ISSUE TITLE
unable to make the scraper to work properly behind corporate proxy

### ISSUE THREAD

**Issue by ad34** [facundoolano/app-store-scraper#12]
at office we have an http proxy  : 

looks like the http_proxy & https_proxy environnement variables are not checked by the module which try direct http access.

**Comment by facundoolano** [comment]
Yeah, I've used superagent instead of request for this (don't remember why now, I think some syntax thing), and it looks like superagent doesn't pick up the environment variables.

Probably the best would be to switch to request.

**Comment by facundoolano** [comment]
I've switched to request on a new version, please let me know if it works for you.
