### ISSUE TITLE
No review date in the review section

### ISSUE THREAD

**Issue by fbamidele1** [facundoolano/app-store-scraper#120]
No review date in the review section

**Comment by facundoolano** [comment]
https://github.com/facundoolano/app-store-scraper/issues/13

**Comment by dasheck0** [comment]
@fbamidele1 Had the same issue. Just released that the xml representation of the data has the updated attribute. See https://itunes.apple.com/us/rss/customerreviews/id=389801252/xml

So you can just parse this data instead and transform it to JSON afterwards. Hope this helps.
