### ISSUE TITLE
the country constants.js doesn't have south Korea ID

### ISSUE THREAD

**Issue by ganzp87** [facundoolano/app-store-scraper#122]
* Operating System: window 10, VS Code
* Node version: 12.14.0
* app-play-scraper version: 0.16.2

### Description: 
When I use list function and set a country as kr, the results show me US contents not KR.
When I use search function and set a country as kr, the results show me empty array

The country constants don't have south Korea ID↓↓↓
https://github.com/facundoolano/app-store-scraper/blob/master/lib/constants.js

You can find the Korea country ID below 
https://github.com/gonzoua/random-stuff/blob/master/appstorereviews.rb
('Korea, Republic Of' => 143466,)

So need to add the missing country ID 'KR' : 143466

### Example code:
```js
import appStore from "app-store-scraper"

const appleApps: AppleApp[] = await appStore.list({
					country: "kr",
					collection: store.collection.TOP_FREE_IPAD,
                                        category: store.category.GAMES_ACTION,
					num: 100,
					fullDetail: true
				})

const appleApps: AppleApp[] = await appStore.search({
					country: "kr",
					term: "food",
                                        page: 3,
					num: 5,
				})
```

### Error message:

```
Error doesn't show
```

**Comment by techinpark** [comment]
@ganzp87 Hello!  Thanks for your issues.  I make a pull request for this issue.  👍
