### ISSUE TITLE
Status code 503 - Does not retrieve the results

### ISSUE THREAD

**Issue by antreasb** [facundoolano/app-store-scraper#135]
* Operating System: macos
* Node version:
* app-play-scraper version: 

### Description: 
It does not retrieve the results from the app store. My json file contains only a response/Status error code 503. I used another VPN but it is still the same. Could you please help me to solve the problem? 

### Error message:

```
response/statusCode 503
```

**Comment by antreasb** [comment]
Please if you could help me  @facundoolano? The script is not working anymore.

**Comment by antreasb** [comment]
Can you help me with my script, please? @Djip @cancuta

**Comment by Djip** [comment]
Well, please explain more about which function you're actually trying to use?

**Comment by antreasb** [comment]
Hi @Djip thank you so much for your reply! Below you can see my script, no matter what my search is, I get a JSON file with the error I mentioned above.

`const readline = require('readline')
const fs = require('fs');
const converter = require('json-2-csv');
var gplay = require('app-store-scraper');


const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

rl.question('Please enter keyword ', (answer) => {
  
	gplay.search({term: answer, num : 50})
  .then(save, save);

  rl.close();
});


function save(json){
	fs.writeFile("test.json", JSON.stringify(json), function (err, data) {
 });}

`

**Comment by Djip** [comment]
@antreasb Did you change the URL in the file, like in this issue: #129 ?
If you're going to use this in a prod environment, you can use my fork, as it's pushed onto that in a new versino

**Comment by antreasb** [comment]
Hi @Djip thank you so much for your help!! :) The Answer to issue #129 solved my problem!

**Comment by facundoolano** [comment]
duplicate of #129
