### ISSUE TITLE
privacy function does not work

### ISSUE THREAD

**Issue by xxccm** [facundoolano/app-store-scraper#162]
### Description: 
I find the new function store.privacy does not work (all other functions works well).
I have installed the latest version by running “npm install app-store-scraper” in cmd

### Example code:
```js
var store = require('app-store-scraper');

store.privacy({
  id: 324684580,
})
.then(console.log)
.catch(console.log);
```

### Error message:
```
TypeError: store.privacy is not a function
```

**Comment by facundoolano** [comment]
I just published v0.17.0 which should include this feature
