### ISSUE TITLE
iTunes will return no data sometimes unless country code is provided.

### ISSUE THREAD

**Issue by danieldram** [facundoolano/app-store-scraper#17]
Hi there,
Thank you so much for putting this package together, saves me a ton of time. It's really great but there is a small issue where with some appIds, unless the country_code is provided in the lookup url, it will return nothing back in the json response even though the app is live in the store. 

I am thinking of making a pull request to add in a feature so you can add the country code similar to how  you can add throttle to the play-store-scrapper. My goal is that if the country code is provided it tacks it on to the url, if not, everything runs normally as it already does. Let me know if this is okay and I'll push up the PR. 

Again, thanks for all your work on this package :) 
Cheers!

**Comment by facundoolano** [comment]
Hi @danieldram . What method are you talking about? `list`, `search`, `similar` and `reviews` already have a `country` parameter.

Also, could you show an actual failing example and how would it be corrected?

Thanks!

**Comment by danieldram** [comment]
Ah nevermind! I see you added it as a query parameter vs a route param in the url, this also works! Sorry, the failing issue I had  is, I was pinging: 1182368306 with the appstore.apps({appId:1182368306}) so the URL requested was: http://itunes.apple.com/lookup?id=1182368306. When country code is provided as &country=code it works as expected. Thanks again for your work on this! Sorry for the  non-issue, my mistake : P

**Comment by facundoolano** [comment]
No problem.
