### ISSUE TITLE
Ramda ReDoS vulnerability, dependency upgrade needed

### ISSUE THREAD

**Issue by jaketrimble** [facundoolano/app-store-scraper#185]
* Operating System: N/A
* Node version: N/A
* app-store-scraper version: 0.17.0

### Description: 
Snyk has identified a vulnerability in **ramada** that is _fixed_ in >0.27.2

View vulnerability [here](https://security.snyk.io/vuln/SNYK-JS-RAMDA-1582370)

**Comment by jbigman** [comment]
Fixed (PR https://github.com/facundoolano/app-store-scraper/pull/196)
