### ISSUE TITLE
bug in extractSuggestions

### ISSUE THREAD

**Issue by rchatterjee** [facundoolano/app-store-scraper#22]
In `extractSuggestions` function in app-store-scraper/lib/suggest.js assumes there is always suggestions. I think it should check before applying list.map. 

```
TypeError: Cannot read property 'map' of undefined
    at extractSuggestions (/Users/rahul/appscraper/node_modules/app-store-scraper/lib/suggest.js:27:14)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```
(I am very new to `nodejs`, and pardon me if it shouold be how it is.)

**Comment by facundoolano** [comment]
Thanks for reporting! Can you give me an example term that causes this to fail?

**Comment by rchatterjee** [comment]
`query = { term: 'hero baby panda bear little boys and girls age 4+',
  throttle: 4 }`
