### ISSUE TITLE
No device as IOS

### ISSUE THREAD

**Issue by rchatterjee** [facundoolano/app-store-scraper#23]
`store.device.IOS` does not exist.

**Comment by facundoolano** [comment]
Correct. I'd really appreciate PRs for this small fixes.

**Comment by danieldram** [comment]
I'd like to help, but I need more information regarding the issue. @rchatterjee can you explain the issue you are having and how to re-produce the bug?

**Comment by danieldram** [comment]
Hi again, 
I was just looking into the code and the API docs from apple, for media type software, I don't see anything related to mobile devices, only similar entity would be 'iPadSoftware' or 'MacSoftware':

[iTunes Affiliate API ](https://affiliate.itunes.apple.com/resources/documentation/itunes-store-web-service-search-api/#searching
)

> software	software, iPadSoftware, macSoftware

I am assuming the edits would be going in the constants.js file? Let me know if there is anything I can do to fix. 

Cheers!

**Comment by facundoolano** [comment]
After some browsing I think there isn't such think as the iOS entity in the itunes search. I tried all the combinations I imagined in the search url and they give me an error, fell free to try it out yourselves, but this looks more like an error in the README.

**Comment by danieldram** [comment]
I agree. I couldn't find it in their docs.

**Comment by facundoolano** [comment]
Fixed README and closing this. Reopen if you find evidence of other relevant devices.
