### ISSUE TITLE
[Question] Languages supported

### ISSUE THREAD

**Issue by csmaiz** [facundoolano/app-store-scraper#3]
Hi @facundoolano, Thanks for sharing app-store-scraper! I'm wondering if it is possible to use it with languages other than English. I'm interested in obtaining search suggestions in Chinese/Japanese.

**Comment by facundoolano** [comment]
All of underlying APIs support other languages, I just never got around adding the options to support them. I'll add it next time I sit down to update this library (PRs are welcome).

**Comment by danieldram** [comment]
I'll help with this! I'll take a look at implementing over the weekend. Least I can do, this is a great package @facundoolano thank you for taking the time to produce it :)

**Comment by zapolnoch** [comment]
Unfortunately, I found that the scraper does not really support other languages when searching. For example:
```
store.search({
  term: 'привет'
}).then(res => {
  console.log(res.length) // return 0
})
```

But if we call encodeURIComponent:
```
store.search({
  term: encodeURIComponent('привет')
}).then(res => {
  console.log(res.length) // return 11
})
```

**Comment by facundoolano** [comment]
How does `encodeURIComponent` affect the search? Would it work to always encode the term?

**Comment by zapolnoch** [comment]
I think that you should always use encodeURIComponent for strings that will be passed as part of the URI. This is necessary to encode the string as a valid URI component.
I did `console.log(response.headers['x-apple-orig-url'])` in [this place](https://github.com/facundoolano/app-store-scraper/blob/9b77f9edfd29d9cfc13197bc169ddfc266e33268/lib/common.js#L48) and received the following results:

`https://itunes.apple.com/search?media=software&entity=software&term=%D0%BF%D1%80%D0%B8%D0%B2%D0%B5%D1%82&limit=50&country=RU`
this is the correct URL. If you do not use encodeURIComponent, you get such a bad result:
`https://itunes.apple.com/search?media=software&entity=software&term=?@825B&limit=50&country=RU`

**Comment by facundoolano** [comment]
This has been open for a while, and it's rather generic, so I'm closing it now. Feel free to reopen more specific issues (e.g. method X doesn't support other languages)
