### ISSUE TITLE
Default value of page param on reviews method

### ISSUE THREAD

**Issue by icaroponce** [facundoolano/app-store-scraper#36]
Is there some special reason for the default value of the `page` param on `reviews` method to be `1` instead of `0`? 

My concerning is about the compatibility with the `google-play-scraper` module.

I think that if we could make it compatible and work the same way, it'd be great for both APIs.

**Comment by facundoolano** [comment]
No special reason, probably just left what the store endpoint is using. You can send a PR changing it if you want.

**Comment by facundoolano** [comment]
fixed by #40
