### ISSUE TITLE
"currentVersionScore" value gone

### ISSUE THREAD

**Issue by iksnae** [facundoolano/app-store-scraper#41]
I just noticed that reviews no longer contain the "currentVersionScore" value. Is this something Apple deprecated or could I be missing something. Thanks!

**Comment by facundoolano** [comment]
mm the code is still there, so if it's missing it probably means it was removed from the itunes response. We'll have to inspect that response to see if it was renamed.

**Comment by iksnae** [comment]
Thank you. That's what I thought.

**Comment by facundoolano** [comment]
I'm going to keep this open since we have to review that field at some point

**Comment by facundoolano** [comment]
Reviewed the payloads and the value is definitely gone, so I'm closing this.
