### ISSUE TITLE
RESTfull Interface

### ISSUE THREAD

**Issue by dkwiebe** [facundoolano/app-store-scraper#43]
We took your Google Play API and ported it to work for the app-store scraper. 
 If you're interested it's available here: https://github.com/lucky42890/App_Store_API-App-Info-

**Comment by facundoolano** [comment]
Interesting. There was actually the idea to add app store endpoints to the google play api (see https://github.com/facundoolano/google-play-api/issues/3).

**Comment by dkwiebe** [comment]
Would you prefer that we implement it like that?  I could gladly get the
developer to go back and do that instead.

**Comment by facundoolano** [comment]
It's totally up to you, I like the idea of having a single API with both stores (and without a front end). But to be honest google-play-api is ver low in my priority list. I'll definitely review any PRs that you may want to send.
