### ISSUE TITLE
implement fullDetail for list

### ISSUE THREAD

**Issue by facundoolano** [facundoolano/app-store-scraper#48]
The new itunes rss feeds returns much less information than before, so a `fullDetail` option should be implemented as it is in google-play-scraper.

make sure memoization properly works for the full detail calls (dont make a request if the app has been called via the app method)

unskip (and fix as necessary) the full detail list test.

**Comment by yakshaving** [comment]
is it even possible to obtain reviews anymore?   doesn't seem like it
