### ISSUE TITLE
Get All Reviews?

### ISSUE THREAD

**Issue by briananderson1222** [facundoolano/app-store-scraper#5]
Is there any way of knowing how many pages are able to be requested? is there a way of requesting all reviews?

**Comment by facundoolano** [comment]
You can get up to 10 pages of reviews per country, which is what apple exposes in their rss feeds.

If you want all you need to get all ten pages for each country.

**Comment by rossmartin** [comment]
~7 years late on this but if anyone wants to get all reviews this can be helpful - https://github.com/rossmartin/app-store-scraper-reviews
