### ISSUE TITLE
Compile to ES5

### ISSUE THREAD

**Issue by lathonez** [facundoolano/app-store-scraper#53]
Hey,

Thanks a lot for your work here - we've been using `app-store-scraper` for some time with our Ionic app.

We have [this issue](https://github.com/webpack/webpack/issues/3928) with our app, the underlying cause being `app-store-scraper`. Until now it only affected development builds and we've just lived with it.

However, on Ionic's latest iteration, it's completely broken, so now our production builds will not run on iOS 9 at all and we need to get our release out ASAP.

After spending some time trying to monkey patch this morning, I've realised that the lesser of several evils was just to release a clone that's compiled to ES5: https://www.npmjs.com/package/app-store-scraper-compat.

I am just raising here for your information. I figured you might not be interested in supporting ES5 anyway.

If you end up releasing a backwards compatible version in the future I'll just kill off `app-store-scraper-compat`.

Thanks

Stephen

**Comment by facundoolano** [comment]
I don't see any code in that repo. Backwards compatibility is not a hard requirement there, but I'd be interested in seeing a diff of what needs to be changed to support it. I don't see it happening if we need to drop arrow functions, though.

**Comment by lathonez** [comment]
Yep, there's no code, it uses the source code from here. You don't need to change anything, just compile with babel.

https://github.com/lathonez/app-store-scraper-compat/blob/master/package.json#L15

Make sense?

**Comment by facundoolano** [comment]
I see. (I'm not very familiar with babel). I'm hesitant to add new development dependencies, I think you can keep your repo around for the purpose of backward compatibility.

If you want you can send a PR adding a link to it in the README.

Closing this one.
