### ISSUE TITLE
Unable to get  reviews sorted as RECENT  

### ISSUE THREAD

**Issue by komalwce** [facundoolano/app-store-scraper#59]
I am trying to sort reviews as RECENT but it is giving me an error.

`TypeError: reviews.slice is not a function`

`var store = require('app-store-scraper'); `
`store.reviews({ id: 'XXXXXXXXX',sort: store.sort.RECENT,page: 2}).then(console.log).catch(console.log);`

**Comment by camnuckols** [comment]
It seems that Apple is no longer returning the entry piece of the review like they used to. Could this be a bug or do you think it happened on purpose?

**Comment by facundoolano** [comment]
What id are you using? Does this happen with any application or just that one? Does it happen if you don't include the sorting parameter?

**Comment by camnuckols** [comment]
It was happening with multiple id's across multiple accounts. I believe that it's happening with all applications. Also, I believe it will happen without the sorting parameter, although I'd need to do more testing with that. I spent a little bit digging into the code last night and `entry` must be coming through as something other than a string or array in the `cleanList` function. 

```function cleanList (results) {
  const reviews = results.feed.entry || [];
  return reviews.slice(1).map((review) => ({
    id: review.id.label,
    userName: review.author.name.label,
    userUrl: review.author.uri.label,
    version: review['im:version'].label,
    score: parseInt(review['im:rating'].label),
    title: review.title.label,
    text: review.content.label,
    url: review.link.attributes.href
  }));
}

**Comment by marxsk** [comment]
I can confirm that it works with store.sort.RECENT perfectly for quite long time. I suggest @facundoolano to close this issue

**Comment by facundoolano** [comment]
thanks @marxsk , closing then.
