### ISSUE TITLE
Is it possible to get retrieve all apps by a given developer name or ID?

### ISSUE THREAD

**Issue by shivy23** [facundoolano/app-store-scraper#72]
You've the functionality to retrieve all apps by a given developer name in your Google Play Scraper script. Can you bring this feature to the app store scraper as well? Please, I'd be so damn happy.

**Comment by facundoolano** [comment]
I don't have time to implement this currently, but I can outline some implementation ideas:

- Simple/slow way: query the web endpoint for developer apps (e.g. https://itunes.apple.com/us/developer/facebook-inc/id284882218?mt=8), extract the resulting app ids and get the details using common.lookup
- Complex/fast way: figure out what API itunes uses internally to fetch apps by developer id, and use that.

**Comment by facundoolano** [comment]
Donde. Thanks for the tip @tdunham02 !
