### ISSUE TITLE
Returning old app info

### ISSUE THREAD

**Issue by Brendan92** [facundoolano/app-store-scraper#73]
After deploying a new version of the IOS app, app-store-scraper returns the previous version with its details.

 Is there a reason that the updated details will take some time to propagate? 

Test case: Opening the app store URL shows the update is live with new version, and the update is available to devices, although app-store-scraper returns the previous version with its details.

I need to check the version immediately when update is live.

App store version:
<img width="310" alt="screenshot 2018-10-01 at 08 45 45" src="https://user-images.githubusercontent.com/16098396/46273596-812efe00-c556-11e8-8787-eb6c733cac67.png">

app-store-scraper version: 
<img width="170" alt="screenshot 2018-10-01 at 08 46 03" src="https://user-images.githubusercontent.com/16098396/46273616-9441ce00-c556-11e8-918c-33932f0654a0.png">

Retrieving app by "id" instead of "appId" seems to make a difference, why would this be the case?

**Comment by facundoolano** [comment]
We're using `https://itunes.apple.com/lookup` to get the app details. My guess is that this search API takes a while longer to update its results. 

using id vs appId changes the field used to query that API (id vs bundleId). Maybe the API behaves differently in each case (you can do some manual searches to verify)

**Comment by Brendan92** [comment]
Thanks, solution currently is to use the "id" instead of "appId". Will do some more testing when I have time.
