### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined 

### ISSUE THREAD

**Issue by Reshail1** [facundoolano/app-store-scraper#93]
Sometimes when I call the "list" method in my nodejs code....
it pops up with this in this console as I am logging the errors. 
I am running node-cron every one minute.

If anyone knows, please help.

TypeError: Cannot read property 'map' of undefined
    at cleanList (/node_modules/app-store-scraper/lib/list.js:10:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by facundoolano** [comment]
Show version of the module (make sure you are using the latest one) and example code to reproduce the issue.

**Comment by Reshail1** [comment]
I am using this version... "app-store-scraper": "^0.6.3". I cannot share the code but can narrate the situation. 
I started node-cron jobs every "one minute" and calling google-play-scraper and app-store-scraper "list" method , one after another. And getting the response and displaying it in the console.

**Comment by facundoolano** [comment]
You're using a two years old version of the code. Update and it should get fixed.
